version: "3.8"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: dbt_user
      POSTGRES_PASSWORD: dbt_pass
      POSTGRES_DB: analytics
    ports:
      - "5432:5432"

  webserver:
    image: apache/airflow:2.10.2
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://dbt_user:dbt_pass@postgres:5432/analytics
      AIRFLOW__CORE__FERNET_KEY: 'my_fernet_key_32charslong1234567890'
    volumes:
      - ./dags:/opt/airflow/dags
    ports:
      - "8080:8080"
